/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as CausesRouteImport } from './routes/causes'
import { Route as CohortsRouteImport } from './routes/cohorts'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DataRouteImport } from './routes/data'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as LifetimeRouteImport } from './routes/lifetime'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as RepeatsRouteImport } from './routes/repeats'
import { Route as ReportRouteImport } from './routes/report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const CausesRoute = CausesRouteImport.update({
  id: '/causes',
  path: '/causes',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortsRoute = CohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const LifetimeRoute = LifetimeRouteImport.update({
  id: '/lifetime',
  path: '/lifetime',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const RepeatsRoute = RepeatsRouteImport.update({
  id: '/repeats',
  path: '/repeats',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/causes': typeof CausesRoute
  '/cohorts': typeof CohortsRoute
  '/cost': typeof CostRoute
  '/data': typeof DataRoute
  '/devices': typeof DevicesRoute
  '/lifetime': typeof LifetimeRoute
  '/parts': typeof PartsRoute
  '/repeats': typeof RepeatsRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/causes': typeof CausesRoute
  '/cohorts': typeof CohortsRoute
  '/cost': typeof CostRoute
  '/data': typeof DataRoute
  '/devices': typeof DevicesRoute
  '/lifetime': typeof LifetimeRoute
  '/parts': typeof PartsRoute
  '/repeats': typeof RepeatsRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/causes': typeof CausesRoute
  '/cohorts': typeof CohortsRoute
  '/cost': typeof CostRoute
  '/data': typeof DataRoute
  '/devices': typeof DevicesRoute
  '/lifetime': typeof LifetimeRoute
  '/parts': typeof PartsRoute
  '/repeats': typeof RepeatsRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/causes'
    | '/cohorts'
    | '/cost'
    | '/data'
    | '/devices'
    | '/lifetime'
    | '/parts'
    | '/repeats'
    | '/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/causes'
    | '/cohorts'
    | '/cost'
    | '/data'
    | '/devices'
    | '/lifetime'
    | '/parts'
    | '/repeats'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/causes'
    | '/cohorts'
    | '/cost'
    | '/data'
    | '/devices'
    | '/lifetime'
    | '/parts'
    | '/repeats'
    | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  CausesRoute: typeof CausesRoute
  CohortsRoute: typeof CohortsRoute
  CostRoute: typeof CostRoute
  DataRoute: typeof DataRoute
  DevicesRoute: typeof DevicesRoute
  LifetimeRoute: typeof LifetimeRoute
  PartsRoute: typeof PartsRoute
  RepeatsRoute: typeof RepeatsRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causes': {
      id: '/causes'
      path: '/causes'
      fullPath: '/causes'
      preLoaderRoute: typeof CausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohorts': {
      id: '/cohorts'
      path: '/cohorts'
      fullPath: '/cohorts'
      preLoaderRoute: typeof CohortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifetime': {
      id: '/lifetime'
      path: '/lifetime'
      fullPath: '/lifetime'
      preLoaderRoute: typeof LifetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repeats': {
      id: '/repeats'
      path: '/repeats'
      fullPath: '/repeats'
      preLoaderRoute: typeof RepeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  CausesRoute: CausesRoute,
  CohortsRoute: CohortsRoute,
  CostRoute: CostRoute,
  DataRoute: DataRoute,
  DevicesRoute: DevicesRoute,
  LifetimeRoute: LifetimeRoute,
  PartsRoute: PartsRoute,
  RepeatsRoute: RepeatsRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
